<?xml version="1.0"?>
<?model_view_type ros2_package?>
<package format="3">
  <name>tecx</name>
  <version>0.0.1</version>
  <description>Custom ROS 2 Python package running on Android Termux</description>
  <maintainer email="cto@tecx.ai">Rahul Saini</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
